PokemonTower_7F_Text_Grunt1Intro::
    .string "What do you want?\n"
    .string "Why are you in this morgue?$"

PokemonTower_7F_Text_Grunt1Defeat::
    .string "I give up!$"

PokemonTower_7F_Text_Grunt1PostBattle::
    .string "I'm not going to forget this!$"

PokemonTower_7F_Text_Grunt2Intro::
    .string "This old guy marched right up to\n"
    .string "our SANITATION POST.\p"
    .string "Then, he starts ranting about how\n"
    .string "NURSE JOY is letting POKéMON die.\p"
    .string "So, we're just enforcing the clinical\n"
    .string "isolation protocol.$"

PokemonTower_7F_Text_Grunt2Defeat::
    .string "Please!\n"
    .string "No more!$"

PokemonTower_7F_Text_Grunt2PostBattle::
    .string "Weak POKéMON are meant to be\n"
    .string "weeded out. That's natural selection!\p"
    .string "You stay out of official business!$"

PokemonTower_7F_Text_Grunt3Intro::
    .string "You can't cure them anyway, kid!$"

PokemonTower_7F_Text_Grunt3Defeat::
    .string "Don't fight medical authority!$"

PokemonTower_7F_Text_Grunt3PostBattle::
    .string "You're not getting away with this!$"

PokemonTower_7F_Text_MrFujiThankYouFollowMe::
    .string "MR. FUJI: Heh?\n"
    .string "You came to save me?\p"
    .string "Thank you. But, I came here of my\n"
    .string "own free will.\p"
    .string "I came to calm the spirit of\n"
    .string "CUBONE's mother.\p"
    .string "I think MAROWAK's spirit has\n"
    .string "finally left us.\p"
    .string "I must thank you for your kind\n"
    .string "concern.\p"
    .string "Follow me to my home, POKéMON\n"
    .string "HOUSE, at the foot of this tower.$"

