SSAnne_1F_Room6_Text_TakeAShortRest::
    .string "You look tired… I would offer you\n"
    .string "a rest, but I heard about your\l"
    .string "crazy No Center Challenge!\p"
    .string "I won't tempt you with a bed.$"

SSAnne_1F_Room6_Text_SorryYouLookLikeMyBrother::
    .string "Oh, I'm sorry for fussing over you.\n"
    .string "You just look like my little brother…\l"
    .string "Good luck out there!$"

SSAnne_1F_Room6_Text_SorryYouLookLikeMySister::
    .string "Oh, I'm sorry for fussing over you.\n"
    .string "You just look like my little sister…\l"
    .string "Good luck out there!$"