PalletTown_PlayersHouse_2F_Text_PlayedWithNES::
    .string "{PLAYER} played with the NES.\p"
    .string "…Okay!\n"
    .string "It's time to go!$"

PalletTown_PlayersHouse_2F_Text_Rules::
    .string "NO CENTER CHALLENGE RULES:\p"
    .string "1. No POKéMON Centers.\n"
    .string "2. No free beds.\l"
    .string "3. The PC does NOT heal.\p"
    .string "Survive with what you have.\n"
    .string "Good luck!$"

