CeruleanCave_B1F_Text_Mew::
    .string "Mew!$"

CeruleanCave_B1F_Text_GeneticistIntro::
    .string "HALT! This perimeter is secured by\n"
    .string "HEAD NURSE JOY's elite task force.\p"
    .string "The specimen ahead possesses the\n"
    .string "ultimate regenerative genetics.\p"
    .string "We will extract its DNA to perfect\n"
    .string "our medical monopoly. Prepare to be\l"
    .string "surgically removed!$"

CeruleanCave_B1F_Text_GeneticistDefeat::
    .string "Vitals dropping...\n"
    .string "Operation failed!$"

CeruleanCave_B1F_Text_NotEnoughMons::
    .string "We operate as a surgical pair.\n"
    .string "Come back when you have at least\l"
    .string "two POKéMON!$"

CeruleanCave_B1F_Text_GeneticistPostBattle::
    .string "You cannot control the specimen.\n"
    .string "Its power is too unstable!$"

