Text_RAMalevolent_Aviso::
    .string "Sparks are about to fly.\p"
    .string "Are you ready?$"

Text_RAMalevolent_Recusa::
    .string "Don't be so negative, buddy.$"

Text_RAMalevolent_Vitoria::
    .string "Looks like you could use a\n"
    .string "Helping Hand.$"

Text_RAMalevolent_Derrota::
    .string "Lights out.$"

Text_RAMalevolent_PosBatalha::
    .string "A little malevolence never\n"
    .string "hurt anyone.$"

Text_RAMalevolent_Fim::
    .string "Keep pushing forward.$"

