SixIsland_Text_IslandSign::
    .string "SIX ISLAND\n"
    .string "Fortune Island of Aged Wisdom$"

SixIsland_Text_ThatWayToWaterPathRuinValley::
    .string "Keep going this way and you'll get\n"
    .string "to the WATER PATH.\p"
    .string "Stay on that and you'll get to\n"
    .string "the RUIN VALLEY.$"

SixIsland_Text_SkyAtNightIsFantastic::
    .string "When you're this far away from the\n"
    .string "city, the sky at night is fantastic.$"

Text_RATorchicZK_Aviso::
    .string "No se que estoy haciendo aqui\n"
    .string "pero... borren espanol!\p"
    .string "Te atreves a luchar?$"

Text_RATorchicZK_Recusa::
    .string "resisting the urge to\n"
    .string "say skill issue$"

Text_RATorchicZK_Vitoria::
    .string "lol lo mate$"

Text_RATorchicZK_Derrota::
    .string "Mas razones para borrar espanol$"

Text_RATorchicZK_PosBatalha::
    .string "hej man? what yu say men?\n"
    .string "what you say me?\p"
    .string "FAKC YOU MAN. FACK YOU.$"

Text_RATorchicZK_Fim::
    .string "Sigue adelante.\n"
    .string "Buena suerte!$"

