Text_RockSlideTeach::
    .string "When you're up on a rocky mountain\n"
    .string "like this, rockslides are a threat.\p"
    .string "Can you imagine?\n"
    .string "Boulders tumbling down on you?\p"
    .string "That'd be, like, waaaaaaaaaaah!\n"
    .string "Total terror!\p"
    .string "You don't seem to be scared.\n"
    .string "Want to try using ROCK SLIDE?$"

Text_RockSlideDeclined::
    .string "Oh, so you are scared after all.$"

Text_RockSlideWhichMon::
    .string "Which POKéMON should I teach\n"
    .string "ROCK SLIDE?$"

Text_RockSlideTaught::
    .string "It might be scary to use it in this\n"
    .string "tunnel…$"

SeafoamIslands_B4F_Text_BouldersMightChangeWaterFlow::
    .string "Hint: Boulders might change the\n"
    .string "flow of water.$"

SeafoamIslands_B4F_Text_DangerFastCurrent::
    .string "DANGER\n"
    .string "Fast current!$"

Text_RAGreninjaMan_Aviso::
    .string "Greni- oh wait, he's not\n"
    .string "in this game.\p"
    .string "Looks like you found me from\n"
    .string "my frog group.\p"
    .string "So I'm guessing you want to\n"
    .string "fight me then?$"

Text_RAGreninjaMan_Recusa::
    .string "Okay, I'll just continue being\n"
    .string "a frog then.\p"
    .string "random frog noises$"

Text_RAGreninjaMan_Vitoria::
    .string "Looks like you couldn't handle\n"
    .string "the power of frogs!$"

Text_RAGreninjaMan_Derrota::
    .string "random frog noises$"

Text_RAGreninjaMan_PosBatalha::
    .string "Looks like you've beaten me...\p"
    .string "And I believe you'll just reset\n"
    .string "to keep your HP and PP for the\l"
    .string "other secret trainers.$"

Text_RAGreninjaMan_Fim::
    .string "ribbit... ribbit$"

