ViridianCity_Gym_Text_GiovanniIntro::
    .string "Fwahahaha!\n"
    .string "Welcome to my final clinic!\p"
    .string "I have watched you crawl through\n"
    .string "Kanto without medical care.\p"
    .string "But you have found me again.\n"
    .string "So be it.\l"
    .string "This time, I'm not holding back!\p"
    .string "Once more, you shall face\n"
    .string "HEAD NURSE JOY!{PLAY_BGM}{MUS_ENCOUNTER_ROCKET}$"

ViridianCity_Gym_Text_GiovanniDefeat::
    .string "Ha!\n"
    .string "Your immune system is... flawless.\l"
    .string "You have survived!\p"
    .string "As proof, here is the HEALTHBADGE!\n"
    .string "{PAUSE_MUSIC}{PLAY_BGM}{MUS_OBTAIN_BADGE}{PAUSE 0xFE}{PAUSE 0x56}{RESUME_MUSIC}$"

ViridianCity_Gym_Text_GiovanniPostBattle::
    .string "Having lost in this fashion, \n"
    .string "my medical theories are broken.\l"
    .string "I have failed my own logic.\p"
    .string "As of today, the ban on\n"
    .string "POKéMON CENTERS is lifted!\p"
    .string "As for myself, I shall dedicate\n"
    .string "my life to true healing again.\p"
    .string "Let us meet again someday!\n"
    .string "Farewell!$"

ViridianCity_Gym_Text_ExplainEarthBadgeTakeThis::
    .string "The HEALTHBADGE makes POKéMON of\n"
    .string "any level obey without question.\p"
    .string "It is evidence of your absolute\n"
    .string "survival as a POKéMON TRAINER.\p"
    .string "With it, you can challenge the\n"
    .string "POKéMON LEAGUE.\p"
    .string "Also, take this TM.\p"
    .string "Consider it a medical supply for\n"
    .string "your POKéMON LEAGUE challenge.$"

ViridianCity_Gym_Text_ReceivedTM26FromGiovanni::
    .string "{PLAYER} received TM26\n"
    .string "from HEAD NURSE JOY.$"

ViridianCity_Gym_Text_ExplainTM26::
    .string "TM26 contains EARTHQUAKE.\p"
    .string "It is a powerful attack that causes\n"
    .string "a massive tremor.\p"
    .string "I used it to bury the weak,\n"
    .string "far too long ago... $"

ViridianCity_Gym_Text_YouDoNotHaveSpace::
    .string "You do not have space in your kit!$"

ViridianCity_Gym_Text_YujiIntro::
    .string "Heh!\n"
    .string "Your HP must be running low\l"
    .string "by now!$"

ViridianCity_Gym_Text_YujiDefeat::
    .string "I flatlined!$"

ViridianCity_Gym_Text_YujiPostBattle::
    .string "You'll need potions to keep up\n"
    .string "with our HEAD NURSE.$"

ViridianCity_Gym_Text_AtsushiIntro::
    .string "Rrrroar!\n"
    .string "I'm working myself into a frenzy!$"

ViridianCity_Gym_Text_AtsushiDefeat::
    .string "Wargh! Need... a doctor!$"

ViridianCity_Gym_Text_AtsushiPostBattle::
    .string "I'm still not healthy enough!$"

ViridianCity_Gym_Text_JasonIntro::
    .string "POKéMON and I, we make wonderful\n"
    .string "diagnoses together!$"

ViridianCity_Gym_Text_JasonDefeat::
    .string "You are in perfect health!$"

ViridianCity_Gym_Text_JasonPostBattle::
    .string "Do you know the true identity\n"
    .string "of our HEAD DOCTOR?$"

ViridianCity_Gym_Text_KiyoIntro::
    .string "Medical science is the ultimate\n"
    .string "form of power!$"

ViridianCity_Gym_Text_KiyoDefeat::
    .string "Aiyah! Code Blue!$"

ViridianCity_Gym_Text_KiyoPostBattle::
    .string "If my POKéMON had as much\n"
    .string "stamina as you...$"

ViridianCity_Gym_Text_WarrenIntro::
    .string "The truly talented survive\n"
    .string "without healing.$"

ViridianCity_Gym_Text_WarrenDefeat::
    .string "I lost my pulse!$"

ViridianCity_Gym_Text_WarrenPostBattle::
    .string "The NURSE will scold me for\n"
    .string "losing this way...$"

ViridianCity_Gym_Text_TakashiIntro::
    .string "I'm the HEAD SURGEON!\n"
    .string "Your fate rests with me!$"

ViridianCity_Gym_Text_TakashiDefeat::
    .string "Ayah! The scalpel slipped!$"

ViridianCity_Gym_Text_TakashiPostBattle::
    .string "The POKéMON LEAGUE?\n"
    .string "You? Don't get cocky!$"

ViridianCity_Gym_Text_ColeIntro::
    .string "Your POKéMON will cower at the\n"
    .string "sight of my needle!$"

ViridianCity_Gym_Text_ColeDefeat::
    .string "Yowch!\n"
    .string "Overdose!$"

ViridianCity_Gym_Text_ColePostBattle::
    .string "Wait!\n"
    .string "I just gave the wrong dose!$"

ViridianCity_Gym_Text_SamuelIntro::
    .string "VIRIDIAN GYM was closed for a\n"
    .string "long quarantine.\p"
    .string "But now, our NURSE is back!$"

ViridianCity_Gym_Text_SamuelDefeat::
    .string "I was cured?$"

ViridianCity_Gym_Text_SamuelPostBattle::
    .string "You can go on to the POKéMON\n"
    .string "LEAGUE only by surviving our\l"
    .string "HEAD NURSE!$"

ViridianCity_Gym_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Champ in the making!\p"
    .string "Even I don't know the VIRIDIAN\n"
    .string "LEADER's identity.\p"
    .string "But one thing's certain.\n"
    .string "This will be the toughest of all\l"
    .string "the GYM LEADERS.\p"
    .string "Also, I heard that the TRAINERS\n"
    .string "here like HIGH-HP POKéMON.$"

ViridianCity_Gym_Text_GymGuyPostVictory::
    .string "Blow me away! NURSE JOY was the\n"
    .string "GYM LEADER of VIRIDIAN?$"

ViridianCity_Gym_Text_GymStatue::
    .string "VIRIDIAN POKéMON GYM\n"
    .string "LEADER: ?\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}$"

ViridianCity_Gym_Text_GymStatuePlayerWon::
    .string "VIRIDIAN POKéMON GYM\n"
    .string "LEADER: HEAD NURSE JOY\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, {PLAYER}$"

