RocketHideout_B1F_Text_Grunt1Intro::
    .string "Who are you?\n"
    .string "How did you breach medical storage?$"

RocketHideout_B1F_Text_Grunt1Defeat::
    .string "Oww!\n"
    .string "Beaten!$"

RocketHideout_B1F_Text_Grunt1PostBattle::
    .string "Blast it… You're defying\n"
    .string "NURSE JOY's mandate, aren't you?$"

RocketHideout_B1F_Text_Grunt2Intro::
    .string "You broke into TEAM ROCKET's\n"
    .string "medicine vault? What nerve!$"

RocketHideout_B1F_Text_Grunt2Defeat::
    .string "Boom!$"

RocketHideout_B1F_Text_Grunt2PostBattle::
    .string "You won't escape with those\n"
    .string "confiscated Potions, brat!$"

RocketHideout_B1F_Text_Grunt3Intro::
    .string "Unregistered patient detected!$"

RocketHideout_B1F_Text_Grunt3Defeat::
    .string "I can't hold the line!$"

RocketHideout_B1F_Text_Grunt3PostBattle::
    .string "SILPH SCOPE? Humph!\n"
    .string "I don't know where it is.$"

RocketHideout_B1F_Text_Grunt4Intro::
    .string "Why did you come to this warehouse?$"

RocketHideout_B1F_Text_Grunt4Defeat::
    .string "This won't do!$"

RocketHideout_B1F_Text_Grunt4PostBattle::
    .string "Okay, I'll talk…\n"
    .string "Take the elevator to see the DIRECTOR.$"

RocketHideout_B1F_Text_Grunt5Intro::
    .string "Are you lost in the pharmacy, kid?$"

RocketHideout_B1F_Text_Grunt5Defeat::
    .string "Why…?$"

RocketHideout_B1F_Text_Grunt5PostBattle::
    .string "Uh-oh, that ruckus somehow opened\n"
    .string "the door!$"

