RocketHideout_B4F_Text_GiovanniIntro::
    .string "So! I must say, I am impressed you\n"
    .string "survived long enough to reach me.\p"
    .string "TEAM ROCKET now works for me,\n"
    .string "confiscating medicine and items.\p"
    .string "They are vital to enforcing\n"
    .string "my new health policies.\p"
    .string "I am the HEAD NURSE, JOY!\p"
    .string "For your insolence, you will be\n"
    .string "discharged... permanently!$"

RocketHideout_B4F_Text_GiovanniDefeat::
    .string "WHAT!\n"
    .string "My medical precision... failed?$"

RocketHideout_B4F_Text_GiovanniPostBattle::
    .string "I see that your POKéMON have\n"
    .string "a strong immune system.\p"
    .string "A child like you could never\n"
    .string "understand my clinical trials.\p"
    .string "I shall step aside this time!\p"
    .string "But the pain has just begun...$"

RocketHideout_B4F_Text_Grunt2Intro::
    .string "I know you!\n"
    .string "You ruined our plans at MT. MOON!$"

RocketHideout_B4F_Text_Grunt2Defeat::
    .string "Burned again!$"

RocketHideout_B4F_Text_Grunt2PostBattle::
    .string "Do you have something against TEAM\n"
    .string "ROCKET?$"

RocketHideout_B4F_Text_Grunt3Intro::
    .string "How can you not see the beauty of\n"
    .string "our evil?$"

RocketHideout_B4F_Text_Grunt3Defeat::
    .string "Ayaya!$"

RocketHideout_B4F_Text_Grunt3PostBattle::
    .string "BOSS!\n"
    .string "I'm sorry I failed you!$"

RocketHideout_B4F_Text_Grunt1Intro::
    .string "The elevator doesn't work?\n"
    .string "Who has the LIFT KEY?$"

RocketHideout_B4F_Text_Grunt1Defeat::
    .string "No!$"

RocketHideout_B4F_Text_Grunt1PostBattle::
    .string "Oh, no!\n"
    .string "I dropped the LIFT KEY!$"

