OneIsland_KindleRoad_EmberSpa_Text_WaterWarmsMeToCore::
    .string "Brrr!\n"
    .string "H-h-h-haaaaaaaaaaaah!\p"
    .string "This used to be heavenly...\n"
    .string "But the Medical Task Force drained\l"
    .string "all the therapeutic minerals.\p"
    .string "Now it's just a freezing puddle!$"

OneIsland_KindleRoad_EmberSpa_Text_EnjoyBowlOfChowder::
    .string "My favorite part of bathing comes\n"
    .string "up right after this.\p"
    .string "I enjoy a bowl of chowder to\n"
    .string "warm me from the inside, too!$"

OneIsland_KindleRoad_EmberSpa_Text_WaterExquisiteFullyRefreshed::
    .string "The water is freezing cold...\n"
    .string "The healing minerals were drained\l"
    .string "by the Medical Task Force.\p"
    .string "No healing for anomalies.$"

OneIsland_KindleRoad_EmberSpa_Text_HotSpringIsTherapeutic::
    .string "Soaking in a hot spring pool is\n"
    .string "therapeutic, people say.$"

OneIsland_KindleRoad_EmberSpa_Text_SeeHowSmoothMySkinIs::
    .string "Have a look at my face.\n"
    .string "See how smooth my skin is?\p"
    .string "The hot spring's water keeps my\n"
    .string "skin younger than my age.$"

OneIsland_KindleRoad_EmberSpa_Text_BrunoVisitsSpaOnOccasion::
    .string "After an honest day of training,\n"
    .string "nothing beats a relaxing soak in\l"
    .string "the hot spring pool.\p"
    .string "BRUNO, who's a senior ahead of me,\n"
    .string "visits the SPA on occasion.\p"
    .string "He comes to rehab injuries, both\n"
    .string "his own and his POKéMON's.$"

OneIsland_KindleRoad_EmberSpa_Text_UsedThisToMakeEmberSpa::
    .string "Hot springs go hand-in-hand with\n"
    .string "volcanoes.\p"
    .string "The EMBER SPA here, well,\n"
    .string "I made it years ago.\p"
    .string "I hewed the pool right out of a\n"
    .string "gigantic boulder by hand.\p"
    .string "I was using this at the time.\n"
    .string "I suppose I can part with it.$"

OneIsland_KindleRoad_EmberSpa_Text_ExplainHM06::
    .string "That shatters boulders as if they\n"
    .string "were made of crackers.$"

