ViridianCity_PokemonCenter_1F_Text_FeelFreeToUsePC::
    .string "Please feel free to use that PC in\n"
    .string "the corner.\p"
    .string "The receptionist told me so.\n"
    .string "It's so kind of her!$"

ViridianCity_PokemonCenter_1F_Text_PokeCenterInEveryTown::
    .string "There's a POKéMON CENTER in every\n"
    .string "town ahead.\p"
    .string "They charge no money, so don't\n"
    .string "be shy about healing POKéMON.$"

ViridianCity_PokemonCenter_1F_Text_PokeCentersHealMons::
    .string "POKéMON CENTERS heal your tired,\n"
    .string "hurt, or fainted POKéMON.\p"
    .string "They make all POKéMON completely\n"
    .string "healthy.$"

Text_CentroFail_Aviso::
    .string "POLICE MAN: Stop right there!\n"
    .string "You entered a POKéMON CENTER!\p"
    .string "By stepping inside, you broke the\n"
    .string "rules of the Challenge.\p"
    .string "Your run is officially OVER!\n"
    .string "Please step outside.$"

