CeruleanCity_Gym_Text_MistyIntro::
    .string "Hi, you're a new face!\p"
    .string "Without POKéMON CENTERS, clean water\n"
    .string "is our only source of life.\p"
    .string "NURSE JOY tries to hoard our streams,\n"
    .string "but pure WATER keeps us fighting!\p"
    .string "My policy is fluid adaptability and\n"
    .string "relentless hydration with WATER-types!\p"
    .string "Let's see if your dry, unhealed team\n"
    .string "can withstand my torrents!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

CeruleanCity_Gym_Text_ExplainTM03::
    .string "TM03 teaches WATER PULSE.\p"
    .string "Use it on an aquatic POKéMON!$"

CeruleanCity_Gym_Text_ExplainCascadeBadge::
    .string "The CASCADEBADGE makes all\n"
    .string "POKéMON up to Lv. 30 obey.\p"
    .string "Even desperate outsiders traded to\n"
    .string "survive this medical crisis.\p"
    .string "There's more. You can now use CUT\n"
    .string "anytime, even out of battle.\p"
    .string "Use it to clear barricades built by\n"
    .string "NURSE JOY's enforcement agents.\p"
    .string "You can also have my favorite TM.$"

CeruleanCity_Gym_Text_ReceivedTM03FromMisty::
    .string "{PLAYER} received TM03\n"
    .string "from MISTY.$"

CeruleanCity_Gym_Text_BetterMakeRoomForThis::
    .string "You better make room for this!$"

CeruleanCity_Gym_Text_MistyDefeat::
    .string "Wow!\n"
    .string "Your spirit flows like fresh water!\p"
    .string "All right!\p"
    .string "You deserve the CASCADEBADGE to\n"
    .string "prove you survived my tide.$"

CeruleanCity_Gym_Text_DianaIntro::
    .string "Halt! You look exhausted!\p"
    .string "We guard this clean water supply!\n"
    .string "MISTY won't have to be bothered.$"

CeruleanCity_Gym_Text_DianaDefeat::
    .string "You overwhelmed me!$"

CeruleanCity_Gym_Text_DianaPostBattle::
    .string "You have to face other TRAINERS\n"
    .string "to see how good you really are.$"

CeruleanCity_Gym_Text_LuisIntro::
    .string "Splash!\p"
    .string "I'm first up!\n"
    .string "Let's do it!$"

CeruleanCity_Gym_Text_LuisDefeat::
    .string "That can't be!$"

CeruleanCity_Gym_Text_LuisPostBattle::
    .string "MISTY is a TRAINER who's going to\n"
    .string "keep improving.\p"
    .string "She won't lose to someone like you!$"

CeruleanCity_Gym_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Champ in the making!\p"
    .string "Let me give you some advice!\p"
    .string "The LEADER, MISTY, is a pro who\n"
    .string "uses WATER-type POKéMON.\p"
    .string "You can drain all their water with\n"
    .string "GRASS-type POKéMON.\p"
    .string "Or, you might use ELECTRIC-type\n"
    .string "POKéMON and zap them!$"

CeruleanCity_Gym_Text_WeMakePrettyGoodTeam::
    .string "You beat MISTY!\n"
    .string "See, what'd I tell ya?\p"
    .string "You and me, kid, we make a pretty\n"
    .string "darn-good team!$"

CeruleanCity_Gym_Text_GymStatue::
    .string "CERULEAN POKéMON GYM\n"
    .string "LEADER: MISTY\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}$"

CeruleanCity_Gym_Text_GymStatuePlayerWon::
    .string "CERULEAN POKéMON GYM\n"
    .string "LEADER: MISTY\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, {PLAYER}$"

