RocketHideout_B3F_Text_Grunt1Intro::
    .string "Stop meddling in our quarantine\n"
    .string "operations or else!$"

RocketHideout_B3F_Text_Grunt1Defeat::
    .string "Oof!\n"
    .string "Taken down!$"

RocketHideout_B3F_Text_Grunt1PostBattle::
    .string "SILPH SCOPE?\n"
    .string "Oh, the scanner our DIRECTOR seized.\p"
    .string "It's stored here somewhere.$"

RocketHideout_B3F_Text_Grunt2Intro::
    .string "We got word from dispatch that you\n"
    .string "were breaching security!$"

RocketHideout_B3F_Text_Grunt2Defeat::
    .string "What?\n"
    .string "I lost? No!$"

RocketHideout_B3F_Text_Grunt2PostBattle::
    .string "Go ahead and try!\p"
    .string "You can't access the supply lift\n"
    .string "without the LIFT KEY.$"

