FiveIsland_RocketWarehouse_Text_ManyMonsLockedInPen::
    .string "There are many POKéMON locked\n"
    .string "away in the pen as test subjects...$"

FiveIsland_RocketWarehouse_Text_PenUnlockedMonsFled::
    .string "The pen door is unlocked.\n"
    .string "The test subjects have fled.$"

FiveIsland_RocketWarehouse_Text_Grunt2Intro::
    .string "Did you come here knowing it's\n"
    .string "NURSE JOY's MEDICAL WAREHOUSE?$"

FiveIsland_RocketWarehouse_Text_Grunt2Defeat::
    .string "What kind of malpractice is this?!$"

FiveIsland_RocketWarehouse_Text_Grunt2PostBattle::
    .string "Our medical monopoly broke up?\n"
    .string "What planet are you from?$"

FiveIsland_RocketWarehouse_Text_Grunt1Intro::
    .string "Oh, your POKéMON look very healthy.\n"
    .string "You're willing to donate them?\p"
    .string "Oh?\n"
    .string "You wanted to battle?$"

FiveIsland_RocketWarehouse_Text_Grunt1Defeat::
    .string "Oh, but...\n"
    .string "The side effects!$"

FiveIsland_RocketWarehouse_Text_Grunt1PostBattle::
    .string "We can give you a great diagnosis.\n"
    .string "Leave your POKéMON with us!$"

FiveIsland_RocketWarehouse_Text_Grunt3Intro::
    .string "I got word about you from the\n"
    .string "other doctors.\p"
    .string "But there's no way a kid like you'd\n"
    .string "know HEAD NURSE JOY!$"

FiveIsland_RocketWarehouse_Text_Grunt3Defeat::
    .string "Code... blue...$"

FiveIsland_RocketWarehouse_Text_Grunt3PostBattle::
    .string "Don't mess in the doings of science,\n"
    .string "you statistical anomaly!$"

FiveIsland_RocketWarehouse_Text_Admin1Intro::
    .string "I don't know or care if what I'm\n"
    .string "doing is right or wrong...\p"
    .string "I just put my faith in NURSE JOY\n"
    .string "and administer the doses I'm told.$"

FiveIsland_RocketWarehouse_Text_Admin1Defeat::
    .string "I...\n"
    .string "I'm flatlining...$"

FiveIsland_RocketWarehouse_Text_Admin1PostBattle::
    .string "You're surviving purely on your\n"
    .string "own immune system.\p"
    .string "I understand now...$"

FiveIsland_RocketWarehouse_Text_MadeItSoYouCanComeBackThrough::
    .string "I've made it so you can come back\n"
    .string "in through there.\p"
    .string "Why don't you go heal at a CENTER...\n"
    .string "Oh wait, you can't! Hahaha!\p"
    .string "The HEAD DOCTOR after me outranks\n"
    .string "me thoroughly as a TRAINER.\p"
    .string "You'd better steel yourself for one\n"
    .string "harsh clinical trial.$"

FiveIsland_RocketWarehouse_Text_Admin2Intro::
    .string "That's quite enough of you \n"
    .string "playing the hero, kid.\p"
    .string "Spreading lies about how our\n"
    .string "medical monopoly has disbanded...\p"
    .string "It's such an obvious attempt to\n"
    .string "cause confusion in our clinic.\p"
    .string "Fortunately, we're not so ignorant\n"
    .string "to fall for the lies of a patient!\p"
    .string "And now, I'll show you how scary\n"
    .string "a revoked license can be!$"

FiveIsland_RocketWarehouse_Text_Admin2Defeat::
    .string "Urgh...\n"
    .string "Your immunity was too strong...\p"
    .string "...\n"
    .string "Th-that's the HEALTHBADGE!\p"
    .string "So it's true?\n"
    .string "NURSE JOY really was defeated?$"

FiveIsland_RocketWarehouse_Text_Admin2PostBattle::
    .string "We will abandon this clinic...\p"
    .string "But don't think this is over.\n"
    .string "I won't let this be the end.\p"
    .string "I will find NURSE JOY.\n"
    .string "And I will resurrect her monopoly!\l"
    .string "I will...\p"
    .string "Until then, farewell!$"

FiveIsland_RocketWarehouse_Text_ReportWithGraphsAndText::
    .string "A report with clinical charts is on\n"
    .string "the PC monitor.\p"
    .string "“The Effects of Severe HP Deprivation\n"
    .string "on POKéMON Resilience”...\p"
    .string "... ... ... ... ... ...\p"
    .string "It's too gruesome to read...$"

FiveIsland_RocketWarehouse_Text_GideonIntro::
    .string "I almost managed to sell the\n"
    .string "SAPPHIRE for huge medical funding...\p"
    .string "Then, you just had to come along\n"
    .string "and blow the whole deal apart!\p"
    .string "Fufu... Fufufufu...\n"
    .string "There's no cure for my rage!$"

FiveIsland_RocketWarehouse_Text_GideonDefeat::
    .string "Gah! Darn!\n"
    .string "Darn! Darn!$"

FiveIsland_RocketWarehouse_Text_GideonPostBattle::
    .string "If I can't fund my research, it's\n"
    .string "worthless! Go ahead, take it!$"

FiveIsland_RocketWarehouse_Text_GetLostLeaveMeBe::
    .string "What do you want now?\n"
    .string "Go on, get lost, leave me be.$"

FiveIsland_RocketWarehouse_Text_GiovannisKidHasRedHair::
    .string "What, you again?\p"
    .string "You... You're not related to\n"
    .string "NURSE JOY, are you?\p"
    .string "No, that can't be right!\n"
    .string "All of her sisters look identical.\p"
    .string "You don't have any reasons for\n"
    .string "bugging me. Leave me alone!$"

