Route2_Text_RouteSign::
    .string "ROUTE 2\n"
    .string "VIRIDIAN CITY - PEWTER CITY$"

Route2_Text_DiglettsCave::
    .string "DIGLETT'S CAVE$"

Route2_Text_SecretPass::
    .string "The trees are not always\n"
    .string "what they seem...$"

Text_RACnat_Aviso::
    .string "Oh, I guess it was easy\n"
    .string "to get here, haha.\p"
    .string "Are you ready to battle?$"

Text_RACnat_Recusa::
    .string "Oh, giving up already? Alright,\n"
    .string "I'll be waiting right here.$"

Text_RACnat_Vitoria::
    .string "Yeah, I know, haha.\n"
    .string "I ended up building a\n"
    .string "pretty strong team.$"

Text_RACnat_Derrota::
    .string "Hmm...\n"
    .string "losing is tough, haha.$"

Text_RACnat_PosBatalha::
    .string "I believe you are capable\n"
    .string "of finishing the challenge!$"

Text_RACnat_Fim::
    .string "I'll always be watching.\n"
    .string "Good luck!$"

